name: Deploy Application to EKS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: your-eks-cluster
  ECR_REPOSITORY: meridian
  DEPLOYMENT_NAME: meridian
  CONTAINER_NAME: meridian
  K8S_NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Install Gitleaks
      - name: Install Gitleaks
        run: |
          GITLEAKS_VERSION="8.21.2"
          curl -sSL "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      # Step 3: Scan repository for secrets
      - name: Run Gitleaks Scan
        run: gitleaks detect --source . --verbose --redact

      #Infrastructure and configuration security scan
      - name: Run Checkov 
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform,kubernetes,cloudformation,dockerfile,secrets
          output_format: cli
          soft_fail: true
      
      # Step 4: Login to AWS using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 5: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      # Step 6: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          echo "Building image..."
          docker build -t $IMAGE_URI .

          echo "Pushing image to Amazon ECR..."
          docker push $IMAGE_URI

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Step 7: Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      # Step 8: Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      # Step 9: Apply Kubernetes manifests
      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8/

      # Step 10: Update deployment image
      - name: Update Deployment Image
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME \
            $CONTAINER_NAME=$IMAGE_URI \
            -n $K8S_NAMESPACE

      # Step 11: Verify rollout
      - name: Check Rollout Status
        run: |
          kubectl rollout status deployment/$DEPLOYMENT_NAME \
            -n $K8S_NAMESPACE