name: Deploy Application to EKS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: your-eks-cluster
  ECR_REPOSITORY: meridian
  DEPLOYMENT_NAME: meridian
  CONTAINER_NAME: meridian
  K8S_NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Login to AWS using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          echo "Building image..."
          docker build -t $IMAGE_URI .

          echo "Pushing image to Amazon ECR..."
          docker push $IMAGE_URI

          # Save the image URI for later steps
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Step 5: Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      # Step 6: Connect to the EKS cluster
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      # Step 7: Apply Kubernetes manifests
      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8/

      # Step 8: Update the deployment with the new image
      - name: Update Deployment Image
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME \
            $CONTAINER_NAME=$IMAGE_URI \
            -n $K8S_NAMESPACE

      # Step 9: Wait until the deployment is successful
      - name: Check Rollout Status
        run: |
          kubectl rollout status deployment/$DEPLOYMENT_NAME \
            -n $K8S_NAMESPACE